# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-21 14:17
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(default='')),
                ('logo', models.TextField(default='')),
                ('founded_on', models.DateField(blank=True, null=True)),
                ('website', models.TextField(default='')),
                ('social_info', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('markets', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=254, null=True), blank=True, null=True, size=None)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('stage', models.CharField(blank=True, max_length=254, null=True)),
                ('investor', models.CharField(blank=True, max_length=254, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inc42.Company')),
            ],
        ),
    ]
